#line 2 "/Users/nakatani.sho/git/smartdb/lib/parser/lexer.c"

#line 4 "/Users/nakatani.sho/git/smartdb/lib/parser/lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	yyleng = (yy_size_t) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 110
#define YY_END_OF_BUFFER 111
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[415] =
    {   0,
        0,    0,  111,  110,  108,  107,  110,   97,   97,   97,
       99,   93,   91,   94,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   98,   98,   98,  108,    0,  106,  105,
        0,  101,    0,  100,   99,    0,   95,   92,   96,   98,
       98,   98,   98,   10,   98,   98,   98,   14,   98,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   98,   98,   44,   49,   98,   98,   98,
       98,   98,   98,   98,   98,   57,   58,   98,   61,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,

       98,   98,   80,   98,   98,   98,   98,   98,   98,   98,
       98,    0,  109,    0,  104,  100,    0,    0,  102,    1,
        2,    3,    9,   11,   98,    4,   98,   98,   98,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   98,   98,   98,   35,   98,   98,    0,
       98,   98,   98,   98,   98,   98,   47,   50,   98,   98,
        6,    5,   98,   54,   98,   98,   98,   98,   98,   98,
       64,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       75,   98,   98,   98,    7,   98,   98,   98,   98,   98,
       98,   98,   98,   98,    0,  103,   98,   98,   15,   98,

       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   28,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   39,    0,   40,   98,   98,   98,   98,   98,
       98,   48,   98,   52,   98,   55,   98,   59,   98,   98,
       98,   98,   98,   98,   98,   98,   70,   98,   98,   98,
       98,   98,   77,   98,   98,   98,   98,   98,   84,   98,
       86,   98,   98,   89,   90,   98,   98,   98,   16,   17,
       18,   98,   98,    8,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   98,   98,   33,   34,   98,   98,   38,
       40,   41,   42,   98,   98,   98,   98,   98,   98,   98,

       98,   62,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   98,   79,   81,   98,   98,   98,   98,
       88,   98,   98,   98,   19,   98,   21,   98,   23,   98,
       98,   98,   27,   98,   30,   31,   32,   98,   98,   43,
       98,   46,   98,   98,   53,   98,   60,   63,   98,   98,
       98,   98,   69,   98,   98,   73,   74,   98,   98,   82,
       83,   85,   98,   98,   13,   98,   98,   22,   24,   25,
       26,   98,   36,   37,   98,   47,   98,   56,   98,   66,
       98,   98,   98,   98,   98,   78,   98,   98,   98,   20,
       29,   98,   51,   98,   98,   98,   98,   72,   76,   87,

       98,   15,   45,   65,   98,   68,   98,   98,   67,   71,
       98,   98,   12,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    5,    6,
        6,    6,    7,    6,    8,    9,    6,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,    6,    6,   11,
       12,   13,    1,    1,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
        1,    1,    1,    1,   40,    1,   41,   42,   43,   44,

       45,   46,   47,   48,   49,   23,   50,   51,   52,   53,
       54,   55,   56,   57,   58,   59,   60,   61,   62,   63,
       64,   65,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[66] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2
    } ;

static yyconst flex_int16_t yy_base[418] =
    {   0,
        0,    0,  207,  852,   64,  852,   64,  852,  195,   60,
       62,   61,  852,  166,   91,   57,  132,   61,   54,  130,
       57,   62,   66,    0,   59,   87,  115,  105,  166,  157,
      122,  208,  187,  141,  188,  218,   80,   87,  852,  852,
      159,  212,   89,  225,  238,  124,  852,  852,  852,    0,
       86,   62,  214,  104,  113,  157,  141,    0,  236,  151,
      248,  188,  159,  260,  186,  211,  216,  239,  232,  241,
      253,  245,  253,  266,  254,  292,    0,  255,  269,  273,
      265,  277,  288,  281,  291,    0,    0,  308,  304,  297,
      305,  316,  316,  333,  308,  314,  312,  325,  320,  324,

      330,  342,    0,  338,  347,  350,  348,  351,  358,  345,
      349,  151,  852,  135,  131,  367,  382,  128,  120,    0,
        0,    0,    0,    0,  360,    0,  347,  357,  370,  361,
      366,  371,  365,  373,  387,  379,  380,  393,  397,  400,
      385,  406,  408,  393,  411,  416,  414,  408,  412,  437,
      412,  414,  411,  411,  428,  434,  435,    0,  435,  438,
        0,    0,  412,    0,  433,  447,  435,  446,  456,  459,
        0,  460,  452,  465,  460,  461,  472,  468,  473,  476,
        0,  472,  480,  483,    0,  480,  479,  486,  475,  476,
      478,  489,  501,  491,  112,   84,  496,  510,  515,  510,

      512,  512,  516,  517,  510,  511,  527,  519,  522,  537,
      519,  521,    0,  536,  536,  533,  531,  538,  534,  546,
      540,  558,    0,  549,    0,  548,  553,  556,  568,  558,
      571,    0,  560,    0,  571,    0,  567,    0,  571,  569,
      578,  579,  590,  583,  588,  588,    0,  581,  598,  590,
      598,  592,    0,  593,  605,  600,  595,  597,    0,  616,
        0,  617,  618,    0,    0,  608,  626,  629,    0,    0,
        0,  615,  622,    0,  628,  624,  621,  640,  626,  633,
      641,  637,  642,  648,  636,    0,    0,  649,  656,    0,
      852,    0,    0,  656,  665,  649,  662,  671,  670,  667,

      664,    0,  667,  663,  667,  674,  683,  685,  684,  690,
      691,  676,  688,  694,    0,    0,  695,  696,  687,  685,
        0,  700,  699,  697,    0,  699,    0,  701,    0,  711,
      705,  706,    0,  726,    0,    0,    0,  717,  720,    0,
      715,    0,  720,  733,    0,  738,    0,    0,  733,  719,
      740,  727,    0,  736,  748,    0,    0,  739,  749,    0,
        0,    0,  750,  732,    0,  754,  757,    0,    0,    0,
        0,  745,    0,    0,  751,    0,  758,    0,  756,    0,
      766,  757,  774,  769,  763,    0,  767,  786,  775,    0,
        0,  776,    0,  781,  783,  791,  793,    0,    0,    0,

      782,    0,    0,    0,  784,    0,  786,  790,    0,    0,
      792,  794,    0,  852,  847,   79,  849
    } ;

static yyconst flex_int16_t yy_def[418] =
    {   0,
      414,    1,  414,  414,  414,  414,  415,  414,  414,  414,
      414,  414,  414,  414,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  414,  415,  414,  414,
      417,  414,  414,  414,  414,  414,  414,  414,  414,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,

      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  417,  414,  414,  414,  414,  414,  414,  414,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  414,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  414,  414,  416,  416,  416,  416,

      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  414,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      414,  416,  416,  416,  416,  416,  416,  416,  416,  416,

      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,

      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,    0,  414,  414,  414
    } ;

static yyconst flex_int16_t yy_nxt[918] =
    {   0,
        4,    5,    6,    5,    7,    8,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   24,
       31,   32,   33,   34,   35,   36,   24,   24,   24,    4,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   25,
       26,   27,   28,   29,   30,   24,   31,   32,   33,   34,
       35,   36,   24,   24,   24,   37,   39,   37,   40,   42,
       44,   45,   47,   48,   57,   75,   78,   43,   64,   46,
       50,   37,   65,   37,   73,   67,  121,   74,   66,   39,
       68,   40,   76,  196,   58,  114,  114,   77,  115,  120,

       79,   57,   75,   78,   43,   64,   46,   51,   80,   65,
       73,   67,  121,   74,   66,   52,   68,   53,   76,  124,
       58,  196,   54,   77,   55,   56,  120,   79,   81,  119,
      118,  118,   84,  119,   51,   80,   82,  119,   85,   94,
      115,   52,   83,   53,  115,  125,  124,   69,   54,   95,
       55,   56,   59,  113,   70,   81,   60,   71,   84,   61,
       72,  113,   62,   82,   85,   63,   94,  104,   83,  105,
       90,  125,  106,  127,   69,   95,  126,   49,  130,   59,
       70,   91,   60,   71,   86,   61,   72,   92,   62,  136,
       93,   63,   87,  104,   88,  105,   89,   90,  106,  127,

      102,  107,   41,  126,  130,  135,  414,   91,  414,  108,
      414,   86,  414,   92,  103,  136,   93,  141,   87,  414,
       88,   42,   89,   96,  414,   97,  414,  102,  107,   43,
      122,  143,  135,   98,  116,   99,  108,  100,  109,  110,
      103,  101,  117,  141,  142,  111,   44,   45,  414,  128,
       96,  123,   97,  129,  150,   46,   43,  122,  143,   98,
      144,   99,  131,  100,  145,  109,  110,  101,  146,  117,
      142,  111,  149,  132,  133,  137,  128,  123,  138,  152,
      129,  134,   46,  147,  139,  151,  148,  144,  154,  131,
      145,  140,  158,  153,  146,  159,  160,  414,  149,  132,

      133,  161,  137,  162,  163,  138,  152,  134,  155,  147,
      139,  151,  148,  164,  154,  165,  166,  140,  158,  153,
      169,  159,  160,  156,  157,  167,  171,  161,  170,  162,
      175,  163,  178,  172,  179,  155,  180,  173,  182,  164,
      168,  165,  166,  174,  181,  183,  176,  169,  184,  156,
      157,  177,  167,  171,  170,  185,  186,  175,  178,  187,
      172,  179,  180,  188,  173,  182,  168,  189,  191,  174,
      181,  183,  190,  176,  184,  192,  116,  193,  177,  194,
      197,  185,  198,  186,  117,  200,  187,  199,  195,  195,
      188,  196,  201,  202,  189,  191,  203,  204,  190,  205,

      206,  209,  192,  193,  210,  194,  211,  197,  198,  207,
      208,  117,  200,  199,  212,  213,  414,  214,  201,  202,
      215,  216,  203,  204,  217,  205,  218,  206,  209,  219,
      210,  220,  228,  211,  222,  207,  208,  223,  150,  225,
      226,  212,  213,  214,  227,  235,  221,  215,  216,  229,
      217,  230,  231,  218,  233,  234,  219,  236,  220,  228,
      222,  238,  232,  223,  237,  225,  226,  239,  414,  224,
      227,  235,  221,  240,  241,  242,  229,  243,  230,  231,
      245,  233,  234,  236,  246,  247,  244,  238,  232,  248,
      250,  237,  249,  251,  239,  224,  252,  253,  254,  258,

      240,  241,  242,  243,  255,  259,  256,  245,  257,  260,
      246,  247,  244,  261,  265,  262,  248,  250,  249,  263,
      251,  264,  252,  266,  253,  254,  258,  267,  268,  270,
      255,  259,  256,  269,  257,  260,  271,  272,  273,  261,
      265,  262,  274,  275,  276,  263,  277,  278,  264,  266,
      279,  414,  280,  281,  267,  268,  270,  282,  286,  269,
      283,  284,  271,  285,  272,  273,  287,  288,  274,  275,
      289,  276,  277,  278,  290,  414,  291,  279,  280,  281,
      292,  293,  294,  295,  282,  286,  283,  284,  296,  285,
      297,  303,  287,  298,  288,  299,  289,  300,  301,  302,

      304,  290,  291,  305,  306,  307,  292,  293,  294,  308,
      295,  309,  310,  312,  296,  311,  313,  297,  303,  298,
      314,  299,  315,  300,  301,  302,  316,  304,  317,  318,
      305,  306,  307,  319,  320,  321,  308,  309,  322,  310,
      312,  311,  313,  323,  324,  327,  314,  325,  326,  315,
      328,  329,  316,  330,  317,  318,  331,  332,  333,  335,
      319,  320,  321,  334,  322,  336,  414,  337,  338,  339,
      323,  324,  327,  325,  326,  340,  328,  329,  341,  343,
      330,  342,  331,  332,  344,  333,  335,  345,  346,  334,
      347,  348,  336,  337,  349,  338,  339,  350,  351,  352,

      353,  354,  340,  355,  356,  341,  343,  342,  357,  358,
      359,  344,  360,  361,  345,  346,  347,  348,  362,  363,
      349,  364,  370,  350,  351,  365,  352,  353,  354,  366,
      355,  356,  367,  368,  357,  369,  358,  359,  371,  360,
      361,  372,  414,  373,  362,  363,  374,  375,  364,  370,
      376,  365,  377,  378,  379,  366,  380,  381,  367,  368,
      382,  369,  383,  384,  371,  385,  386,  387,  372,  373,
      388,  389,  374,  375,  390,  393,  376,  391,  392,  377,
      378,  379,  380,  394,  381,  395,  382,  396,  383,  397,
      384,  385,  398,  386,  387,  399,  388,  400,  389,  401,

      405,  390,  393,  391,  392,  402,  403,  404,  406,  394,
      407,  411,  395,  396,  408,  409,  397,  410,  398,  412,
      413,  399,  414,  400,  414,  414,  401,  405,  414,  414,
      414,  402,  403,  404,  414,  406,  414,  407,  411,  414,
      408,  409,  414,  410,  414,  412,  413,   38,   38,  112,
      112,    3,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,

      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414
    } ;

static yyconst flex_int16_t yy_chk[918] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    7,    5,    7,   10,
       11,   11,   12,   12,   16,   22,   25,   10,   18,   11,
      416,   37,   18,   37,   21,   19,   52,   21,   18,   38,
       19,   38,   23,  196,   16,   43,   43,   23,   43,   51,

       26,   16,   22,   25,   10,   18,   11,   15,   26,   18,
       21,   19,   52,   21,   18,   15,   19,   15,   23,   54,
       16,  195,   15,   23,   15,   15,   51,   26,   27,  119,
       46,   46,   28,   46,   15,   26,   27,  118,   28,   31,
      115,   15,   27,   15,  114,   55,   54,   20,   15,   31,
       15,   15,   17,  112,   20,   27,   17,   20,   28,   17,
       20,   41,   17,   27,   28,   17,   31,   34,   27,   34,
       30,   55,   34,   57,   20,   31,   56,   14,   60,   17,
       20,   30,   17,   20,   29,   17,   20,   30,   17,   63,
       30,   17,   29,   34,   29,   34,   29,   30,   34,   57,

       33,   35,    9,   56,   60,   62,    3,   30,    0,   35,
        0,   29,    0,   30,   33,   63,   30,   65,   29,    0,
       29,   42,   29,   32,    0,   32,    0,   33,   35,   42,
       53,   67,   62,   32,   44,   32,   35,   32,   36,   36,
       33,   32,   44,   65,   66,   36,   45,   45,    0,   59,
       32,   53,   32,   59,   73,   45,   42,   53,   67,   32,
       68,   32,   61,   32,   69,   36,   36,   32,   70,   44,
       66,   36,   72,   61,   61,   64,   59,   53,   64,   74,
       59,   61,   45,   71,   64,   73,   71,   68,   75,   61,
       69,   64,   78,   74,   70,   79,   80,    0,   72,   61,

       61,   81,   64,   82,   83,   64,   74,   61,   76,   71,
       64,   73,   71,   84,   75,   85,   85,   64,   78,   74,
       89,   79,   80,   76,   76,   88,   91,   81,   90,   82,
       93,   83,   95,   92,   96,   76,   97,   92,   98,   84,
       88,   85,   85,   92,   97,   99,   94,   89,  100,   76,
       76,   94,   88,   91,   90,  101,  102,   93,   95,  104,
       92,   96,   97,  105,   92,   98,   88,  106,  108,   92,
       97,   99,  107,   94,  100,  109,  116,  110,   94,  111,
      125,  101,  127,  102,  116,  129,  104,  128,  117,  117,
      105,  117,  130,  131,  106,  108,  132,  133,  107,  134,

      135,  137,  109,  110,  137,  111,  138,  125,  127,  136,
      136,  116,  129,  128,  139,  140,    0,  141,  130,  131,
      142,  143,  132,  133,  144,  134,  145,  135,  137,  146,
      137,  147,  154,  138,  148,  136,  136,  149,  150,  151,
      152,  139,  140,  141,  153,  163,  147,  142,  143,  155,
      144,  156,  157,  145,  159,  160,  146,  165,  147,  154,
      148,  167,  157,  149,  166,  151,  152,  168,    0,  150,
      153,  163,  147,  169,  170,  172,  155,  173,  156,  157,
      174,  159,  160,  165,  175,  176,  173,  167,  157,  177,
      179,  166,  178,  180,  168,  150,  182,  183,  184,  188,

      169,  170,  172,  173,  186,  189,  187,  174,  187,  190,
      175,  176,  173,  191,  194,  192,  177,  179,  178,  192,
      180,  193,  182,  197,  183,  184,  188,  198,  199,  201,
      186,  189,  187,  200,  187,  190,  202,  203,  204,  191,
      194,  192,  205,  206,  207,  192,  208,  209,  193,  197,
      210,    0,  211,  212,  198,  199,  201,  214,  218,  200,
      215,  216,  202,  217,  203,  204,  219,  220,  205,  206,
      221,  207,  208,  209,  222,    0,  224,  210,  211,  212,
      226,  227,  228,  229,  214,  218,  215,  216,  230,  217,
      231,  241,  219,  233,  220,  235,  221,  237,  239,  240,

      242,  222,  224,  243,  244,  245,  226,  227,  228,  246,
      229,  248,  249,  251,  230,  250,  252,  231,  241,  233,
      254,  235,  255,  237,  239,  240,  256,  242,  257,  258,
      243,  244,  245,  260,  262,  263,  246,  248,  266,  249,
      251,  250,  252,  267,  268,  275,  254,  272,  273,  255,
      276,  277,  256,  278,  257,  258,  279,  280,  281,  283,
      260,  262,  263,  282,  266,  284,    0,  285,  288,  289,
      267,  268,  275,  272,  273,  294,  276,  277,  295,  297,
      278,  296,  279,  280,  298,  281,  283,  299,  300,  282,
      301,  303,  284,  285,  304,  288,  289,  305,  306,  307,

      308,  309,  294,  310,  311,  295,  297,  296,  312,  313,
      314,  298,  317,  318,  299,  300,  301,  303,  319,  320,
      304,  322,  331,  305,  306,  323,  307,  308,  309,  324,
      310,  311,  326,  328,  312,  330,  313,  314,  332,  317,
      318,  334,    0,  338,  319,  320,  339,  341,  322,  331,
      343,  323,  344,  346,  349,  324,  350,  351,  326,  328,
      352,  330,  354,  355,  332,  358,  359,  363,  334,  338,
      364,  366,  339,  341,  367,  377,  343,  372,  375,  344,
      346,  349,  350,  379,  351,  381,  352,  382,  354,  383,
      355,  358,  384,  359,  363,  385,  364,  387,  366,  388,

      395,  367,  377,  372,  375,  389,  392,  394,  396,  379,
      397,  408,  381,  382,  401,  405,  383,  407,  384,  411,
      412,  385,    0,  387,    0,    0,  388,  395,    0,    0,
        0,  389,  392,  394,    0,  396,    0,  397,  408,    0,
      401,  405,    0,  407,    0,  411,  412,  415,  415,  417,
      417,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,

      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
#line 2 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
/*
 * AT&T lex can't handle this lexer due to lex bugs.  It works with flex
 * 2.3.7, pclex 2.0.5, and MKS lex 3.1a.
 */


#include "parser.hpp"
#include <string.h>

int yywrap() { return 1; }

int lineno = 1;
extern void yyerror(const char *s);

/* MKS needs the next line to increase the NFA table */
#line 811 "/Users/nakatani.sho/git/smartdb/lib/parser/lexer.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 20 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"


	/* literal keyword tokens */

#line 998 "/Users/nakatani.sho/git/smartdb/lib/parser/lexer.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (yy_c_buf_p) - (yytext_ptr);
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 415 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 852 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 24 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return ADA; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 25 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return ALL; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 26 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return AND; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 27 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return AMMSC; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 28 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return AMMSC; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 29 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return AMMSC; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 30 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return AMMSC; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 31 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return AMMSC; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 32 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return ANY; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 33 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return AS; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 34 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return ASC; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 35 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return AUTHORIZATION; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 36 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return BETWEEN; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 37 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return BY; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 38 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return CHARACTER; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 39 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return CHECK; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 40 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return CLOSE; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 41 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return COBOL; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 42 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return COMMIT; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 43 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return CONTINUE; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 44 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return CREATE; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 45 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return CURRENT; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 46 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return CURSOR; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 47 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return DECIMAL; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 48 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return DECLARE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 49 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return DEFAULT; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 50 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return DELETE; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 51 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return DESC; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 52 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return DISTINCT; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 53 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return DOUBLE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 54 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return ESCAPE; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 55 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return EXISTS; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 56 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return FETCH; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 57 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return FLOAT; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 58 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return FOR; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 59 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return FOREIGN; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 60 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return FORTRAN; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 61 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return FOUND; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 62 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return FROM; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 63 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return GOTO; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 64 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return GRANT; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 65 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return GROUP; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 66 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return HAVING; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 67 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return IN; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 68 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return INDICATOR; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 69 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return INSERT; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 70 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return INTEGER; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 71 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return INTO; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 72 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return IS; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 73 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return KEY; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 74 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return LANGUAGE; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 75 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return LIKE; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 76 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return MODULE; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 77 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return NOT; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 78 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return NULLX; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 79 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return NUMERIC; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 80 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return OF; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 81 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return ON; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 82 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return OPEN; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 83 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return OPTION; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 84 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return OR; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 85 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return ORDER; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 86 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return PASCAL; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 87 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return PLI; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 88 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return PRECISION; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 89 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return PRIMARY; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 90 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return PRIVILEGES; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 91 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return PROCEDURE; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 92 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return PUBLIC; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 93 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return REAL; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 94 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return REFERENCES; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 95 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return ROLLBACK; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 96 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return SCHEMA; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 97 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return SELECT; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 98 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return SET; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 99 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return SMALLINT; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 100 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return SOME; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 101 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return SQLCODE; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 102 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return TABLE; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 103 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return TO; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 104 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return UNION; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 105 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return UNIQUE; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 106 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return UPDATE; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 107 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return USER; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 108 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return VALUES; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 109 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return VIEW; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 110 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return WHENEVER; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 111 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return WHERE; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 112 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return WITH; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 113 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return WORK; }
	YY_BREAK
/* punctuation */
case 91:
#line 118 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
case 92:
#line 119 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
case 93:
#line 120 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
case 94:
#line 121 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
case 95:
#line 122 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
case 96:
YY_RULE_SETUP
#line 122 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return COMPARISON; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 124 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return yytext[0]; }
	YY_BREAK
/* names */
case 98:
YY_RULE_SETUP
#line 128 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return NAME; }
	YY_BREAK
/* numbers */
case 99:
#line 133 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
case 100:
#line 134 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
case 101:
YY_RULE_SETUP
#line 134 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return INTNUM; }
	YY_BREAK
case 102:
#line 137 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
case 103:
#line 138 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
case 104:
YY_RULE_SETUP
#line 138 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ return APPROXNUM; }
	YY_BREAK
/* strings */
case 105:
YY_RULE_SETUP
#line 142 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{
		int c = input();

		unput(c);	/* just peeking */
		if(c != '\'') {
			return STRING;
		} else
			yymore();
	}
	YY_BREAK
case 106:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 152 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
{ yyerror("Unterminated string"); }
	YY_BREAK
case 107:
/* rule 107 can match eol */
YY_RULE_SETUP
#line 154 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
lineno++;
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 156 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
;	/* white space */
	YY_BREAK
case 109:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 158 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
;	/* comment */
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 160 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"
ECHO;
	YY_BREAK
#line 1629 "/Users/nakatani.sho/git/smartdb/lib/parser/lexer.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 415 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 415 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 414);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 160 "/Users/nakatani.sho/git/smartdb/parser/lexer.l"



extern
void yyerror(const char *s)
{
	fprintf(stderr, "%d: %s at %s\n", lineno, s, yytext);
}

/* int main() */
/* { */
/* 	if(!yyparse()) */
/* 		printf("SQL parse worked\n"); */
/* 	else */
/* 		printf("SQL parse failed\n"); */
/* 	return 0; */
/* } */

