language: cpp
compiler:
  - gcc
  - clang

before_install:
  # C++11 feature (e.g. std::unordered_map)
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test ; fi
  - sudo apt-get update -qq

  - sudo apt-get -y install gdb
install:
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8 ; export CXX="g++-4.8" ; fi

  - ulimit -c

before_script:
  - wget https://googletest.googlecode.com/files/gtest-1.7.0.zip && unzip gtest-1.7.0.zip && mv gtest-1.7.0 contrib/gtest
  - wget https://csv-parser-cplusplus.googlecode.com/files/libcsv_parser%2B%2B-1.0.0.tar.bz2 && tar xvf libcsv_parser++-1.0.0.tar.bz2 && (cd libcsv_parser++-1.0.0/ ; ./configure && make && sudo make install)

  - ulimit -c unlimited -S
script:
  # build & install libsmartdb
  - cmake . && make VERBOSE=1 && sudo make install
  # build & install 1st-party storage engines
  - (cd storage/csv ; cmake . && make VERBOSE=1 && sudo make install)
  # build & run test
  - (cd test/unit ; cmake . && make VERBOSE=1 && LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib ./run_gtest)

  - for i in $(find ./ -name 'core*' -print); do gdb $(pwd)/test core* -ex "thread apply all bt" -ex "set pagination 0" -batch; done;

notifications:
  email:
    recipients:
      - lay.sakura@gmail.com
    on_success: change
    on_failure: always
env:
  - LANG="en_US.UTF-8"
os:
  - linux
  - osx
osx_image: xcode61
